version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./site/:/var/www/html
            - ./logs/:/var/log/nginx
            - ./confs/:/etc/nginx/conf.d
        ports:
            - "8888:80"
        networks:
            - code-network
networks:
    code-network:
      driver: bridge
