// datas no js são objetos

var d = new Date();
console.log(d);

//var e = new Date(year, month, day, hours, minutes, seconds, milliseconds)
var e = new Date(2018, 0, 28, 11, 50);
console.log(e);


console.log(d.getDate())
console.log(d.getDay())
console.log(d.getFullYear())
console.log(d.getHours())
console.log(d.getMilliseconds())
console.log(d.getMinutes())
console.log(d.getMonth())
console.log(d.getSeconds())
console.log(d.getTime())
console.log(d.getTimezoneOffset())
//console.log(d.getUTCDate())
console.log(d.getUTCDay())
console.log(d.getUTCFullYear())
console.log(d.getUTCHours())
console.log(d.getUTCMilliseconds())
console.log(d.getUTCMinutes())
console.log(d.getUTCMonth())
console.log(d.getUTCSeconds())
console.log(d.getYear())
//console.log(d.now())
//console.log(d.parse())
console.log(d.setDate())
console.log(d.setFullYear())
console.log(d.setHours())
console.log(d.setMilliseconds())
console.log(d.setMinutes())
console.log(d.setMonth())
console.log(d.setSeconds())
console.log(d.setTime())
console.log(d.setUTCDate())
console.log(d.setUTCFullYear())
console.log(d.setUTCHours())
console.log(d.setUTCMilliseconds())
console.log(d.setUTCMinutes())
console.log(d.setUTCMonth())
console.log(d.setUTCSeconds())
console.log(d.setYear())
console.log(d.toDateString())
console.log(d.toGMTString())
//console.log(d.toISOString())
console.log(d.toJSON())
console.log(d.toLocaleDateString())
console.log(d.toLocaleTimeString())
console.log(d.toLocaleString())
console.log(d.toString())
console.log(d.toTimeString())
console.log(d.toUTCString())
//console.log(d.UTC())
console.log(d.valueOf())